---

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: false
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - memcached

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
  with_items:
    - memcached.conf
  notify:
    - restart memcached
  tags: memcache_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - memcached
